### ISSUE TITLE
What we display to the user when the Places API fails to return an address

### ISSUE THREAD

**Issue by jrmedd** [ebss-alpha/alpha-prototype#50]
In the flow we take the user straight to the manual entry, but I've also suggested we use [one of these](https://design-system.service.gov.uk/components/notification-banner/) at the same time (rather than an error message as it's not strictly an error the user has made) to let them know we were unable to determine their address. 

We need to think of the content for this and to pass it onto Stu.

**Comment by eleanorgrigson** [comment]
The address could not be found. Enter your address manually.

**Comment by jrmedd** [comment]
Closing as the message has been passed along to the dev team.
