### ISSUE TITLE
Ineligible postcode page

### ISSUE THREAD

**Issue by jrmedd** [ebss-alpha/alpha-prototype#54]
As part of our private beta rollout, we're going to need a page that informs a user that the address/postcode they have entered is not within one of the participating local authorities.

## Considerations

* As we've moved the address question back a few pages, the user will have already answered a handful of questions ahead of reaching this page
* As the user may need to enter their address manually, the address lookup will need to happen after the manual address lookup to verify their local authority
* What do we tell a user if their address is not within a local authority? Can we notify them when the service goes live in their area?
* Do we need something on one of the earlier pages (start page or first question) to explain to the user that only certain postcodes are in scope
* What if our lookup fails to correctly identify their local authority, but the user feels they are included?

**Comment by eleanorgrigson** [comment]
Participating: Wrexham (Wales)​

Glasgow (Scotland)​

Chichester (England)​

West Suffolk, Anglia Revenues Partnership (ARP) (Partnership of 5, only 1 will be taking part)

**Comment by eleanorgrigson** [comment]
Wrexham County Borough Council, Glasgow City Council, Chichester District Council and West Suffolk Council

**Comment by eleanorgrigson** [comment]
The service is currently only available in certain areas 

You can currently only use this service if you live in:  

- Chichester District Council 
- Glasgow City Council 
- West Suffolk Council 
- Wrexham County Borough Council 

All other eligible households will be able to use the service from Xam on XX Xday January 2023.
