### ISSUE TITLE
Bank account eligibility content

### ISSUE THREAD

**Issue by jrmedd** [ebss-alpha/alpha-prototype#57]
We need to address content around bank accounts based on the decision to only allow applications from people with bank accounts:

## Pages to address

* [`do-you-have-a-bank-account`](https://github.com/ebss-alpha/alpha-prototype/blob/main/app/views/do-you-have-a-bank-account.html)
* [`get-a-bank-account`](https://github.com/ebss-alpha/alpha-prototype/blob/main/app/views/get-a-bank-account.html)

**Comment by eleanorgrigson** [comment]
Added termination page content

**Comment by eleanorgrigson** [comment]
Updated content around bank names
